<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" xml:lang="sv_SE" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="content-type" content="application/xhtml+xml;charset=utf-8" />
	<title>HAR file decoder</title>
</head>
<body>
<p>This tool is made to parse out urls from files generated by <a href="http://www.softwareishard.com/blog/consoleexport/">Firebug ConsoleExport</a></p><br />
<form action="/har/parser.php" method="post" enctype="multipart/form-data">
<label for="f">Upload HAR file: </label><input type="file" name="f" id="f" />
<input type="submit" value="Parse" />
</form><br /><br/>
<p>As it was requested, below is the source for this tool.</p>
<hr />
<h3>This file</h3>
<?php show_source(__FILE__); ?>
<hr />
<h3>Parser</h3>
<?php show_source("parser.php"); ?>
</body>
</html>
